name: focus_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.19.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.3.0
  focus_client:
    path: ../focus_client
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  clerk_flutter:
    git:
      url: https://github.com/drexel-ue/clerk-sdk-flutter.git
      ref: main
      path: packages/clerk_flutter
  clerk_auth:
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_lorem: ^2.0.0
  collection: ^1.19.0
  flutter_slidable: ^3.1.2

dependency_overrides:
  clerk_auth:
    git:
      url: https://github.com/drexel-ue/clerk-sdk-flutter.git
      ref: main
      path: packages/clerk_auth

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: 'assets/icon/icon.png'
  android: true
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: 'assets/icon/icon_adaptive_fg.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/svgs/
